version: "3"
services:
  factorio-server-manager:
    image: "ghcr.io/dnaroma/factorio-server-manager:latest"
    container_name: "factorio-server-manager"
    restart: "unless-stopped"
    environment:
      - "RCON_PASS"
      - "FSM_ADMIN_USERNAME"
      - "FSM_ADMIN_PASSWORD"
    ports:
      - "80:80"
      - "34197:34197/udp"
    volumes:
      - "./fsm-data:/opt/fsm-data"
      - "./factorio-data:/opt/factorio"
      - "./factorio-data/mod_packs:/opt/fsm/mod_packs"
