on:
  release:
    types: [published]
permissions:
  contents: write
  packages: write
jobs:
  add-assets-to-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: '26.3.1'
      - run: corepack enable
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26.4'
          cache-dependency-path: src/go.sum
      - name: Create release bundles
        run: make gen_release
      - name: Upload release (linux)
        run: gh release upload "$GITHUB_REF_NAME" ./build/factorio-server-manager-linux.zip#factorio-server-manager-linux-$GITHUB_REF_NAME.zip --clobber
        env:
          GH_TOKEN: ${{ github.token }}
  docker-push:
    needs: ['add-assets-to-release']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        run: echo "$GH_TOKEN" | docker login ghcr.io --username "$GITHUB_ACTOR" --password-stdin
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Build and push Docker image
        run: |
          docker buildx build \
            --file ./Dockerfile \
            --provenance=false \
            --tag ghcr.io/dnaroma/factorio-server-manager:latest \
            --tag ghcr.io/dnaroma/factorio-server-manager:$GITHUB_REF_NAME \
            --push \
            .
